// <auto-generated />
namespace TaxiBooking.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _passwordadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_passwordadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202110121140027__passwordadded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
